extern float WINDOW_WIDTH;
extern float WINDOW_HEIGHT;

extern float WINDOW_ASPECT_RATIO;

extern bool GRAPHICS_OPTION_VSYNC;
extern float GRAPHICS_OPTION_WINDOW_WIDTH;
extern float GRAPHICS_OPTION_WINDOW_HEIGHT;
extern float GRAPHICS_OPTION_FOV_DEGREES;

extern float GAME_OPTION_TILE_VIEW_HEIGHT;
extern float GAME_OPTION_MOUSE_SENSITIVITY_X;
extern float GAME_OPTION_MOUSE_SENSITIVITY_Y;
extern bool GAME_OPTION_INVERT_MOUSE_Y;