#include "Game/GameConfig.hpp"

float WINDOW_WIDTH = 1600.0f;
float WINDOW_HEIGHT = 900.0f;

float WINDOW_ASPECT_RATIO = WINDOW_WIDTH / WINDOW_HEIGHT;

bool GRAPHICS_OPTION_VSYNC = true;
float GRAPHICS_OPTION_WINDOW_WIDTH = WINDOW_WIDTH;
float GRAPHICS_OPTION_WINDOW_HEIGHT = WINDOW_HEIGHT;
float GRAPHICS_OPTION_FOV_DEGREES = 70.0f;

float GAME_OPTION_MOUSE_SENSITIVITY_X = 0.1f;
float GAME_OPTION_MOUSE_SENSITIVITY_Y = 0.1f;
bool GAME_OPTION_INVERT_MOUSE_Y = false;